### ISSUE TITLE
TestFormatPath Failed

### ISSUE THREAD

**Issue by NeverRaR** [kcl-lang/kclvm-go#75]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
OS: ubuntu:20.04
python version: 3.9.10
run command : go test  -run ^TestFormatPath$ kusionstack.io/kclvm-go/pkg/tools/format

### 2. What did you expect to see? (Required)
Go test succeeded
### 3. What did you see instead (Required)
```
format_test.go:69: format path exec failed. KCL Compile Error[E2L23] : A complie error occurs during compiling
        ---> File /home/runner/work/kclvm-go/kclvm-go/pkg/tools/format/testdata/success/hello.k -> Failure
        [Errno 32] Broken pipe: stderr = KCL format done and 2 files were formatted:
```

### 4. What is your KusionStack components version? (Required)
v0.4.4-alpha.2

**Comment by jakezhu9** [comment]
Hi! Thanks a lot for bringing up this issue. I discovered that the problem is because we're using an incorrect length when writing to the limitBuffer.

https://github.com/KusionStack/kclvm-go/blob/f2813c3b3e867910a44bd251fa6d1a400cc8e8e1/pkg/kclvm_runtime/proc.go#L112

I will make a pr to fix it soon
